# 配置服务器端口
server:
  port: 8081
#  配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #注意这里是mysql5的驱动，如果是mysql8选择另一个
    username: root
    password: 123456
    #    这里的url别忘记填写数据库名
    url: jdbc:mysql://localhost:3306/sun?useSSL=false&useUnicode=true&characterEncoding=UTF-8
  application:
    name: user-center #这个名字一般是用来做微服务的服务名，用来标识某个服务的，与项目名保持一致即可
